package com.example.giangdam.buydesireex1.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "DBUSER".
 */
public class DBUser {

    private Long id;
    /** Not-null value. */
    private String email;
    /** Not-null value. */
    private String password;
    /** Not-null value. */
    private String firstname;
    /** Not-null value. */
    private String lastname;
    private String gender;
    private String profilename;
    private String aboutme;
    private String websiteurl;

    public DBUser() {
    }

    public DBUser(Long id) {
        this.id = id;
    }

    public DBUser(Long id, String email, String password, String firstname, String lastname, String gender, String profilename, String aboutme, String websiteurl) {
        this.id = id;
        this.email = email;
        this.password = password;
        this.firstname = firstname;
        this.lastname = lastname;
        this.gender = gender;
        this.profilename = profilename;
        this.aboutme = aboutme;
        this.websiteurl = websiteurl;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getEmail() {
        return email;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setEmail(String email) {
        this.email = email;
    }

    /** Not-null value. */
    public String getPassword() {
        return password;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setPassword(String password) {
        this.password = password;
    }

    /** Not-null value. */
    public String getFirstname() {
        return firstname;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setFirstname(String firstname) {
        this.firstname = firstname;
    }

    /** Not-null value. */
    public String getLastname() {
        return lastname;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setLastname(String lastname) {
        this.lastname = lastname;
    }

    public String getGender() {
        return gender;
    }

    public void setGender(String gender) {
        this.gender = gender;
    }

    public String getProfilename() {
        return profilename;
    }

    public void setProfilename(String profilename) {
        this.profilename = profilename;
    }

    public String getAboutme() {
        return aboutme;
    }

    public void setAboutme(String aboutme) {
        this.aboutme = aboutme;
    }

    public String getWebsiteurl() {
        return websiteurl;
    }

    public void setWebsiteurl(String websiteurl) {
        this.websiteurl = websiteurl;
    }

}
